# Generated by Django 3.1.2 on 2020-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfoods',
            name='food',
        ),
        migrations.AddField(
            model_name='customerfoods',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
