# Generated by Django 3.1.2 on 2020-10-31 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calories_app', '0002_auto_20201031_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfoods',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerfoods',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='calories_app.customer'),
        ),
    ]
